### ISSUE TITLE
Got invalid value wrong interpretation

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphql-core-next#12]
Code in graphql-core
https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/values.py#L71-L76

Code in graphql-core-next: 
https://github.com/graphql-python/graphql-core-next/blob/master/graphql/execution/values.py#L96-L99

Graphql-core next leaks the inner Python representation of an object.

In general, after reviewing a lot of tests and code, there is a lot of usage of `repr` when it should be used just for debugging, not for uniform error messages.

**Comment by Cito** [comment]
GraphQL.js uses the [inspect](https://github.com/graphql/graphql-js/blob/master/src/jsutils/inspect.js) function to print values in error messages which also leaks some details like function names. Maybe we should add our own inspect function to pyutils and use it everywhere? Then we can easily modify what we expose in all error messages in a central location. I'd also like to keep close to GraphQL.js.

**Comment by syrusakbary** [comment]
That would be great!

**Comment by Cito** [comment]
I'll get that into the next release then.

**Comment by Cito** [comment]
The problem with the approach in graphql-core of simply JSON dumping values is that the actual error message is not shown when JSON dumping is not possible, instead you get a JSON error. Demonstration:

```python3
import graphql

schema = graphql.build_ast_schema(graphql.parse(
    "schema { query: T } input I { n: Int! } type T { s(i: I!): String }"))
query = "query ($i: I!) { s(i: $i) }"
result = graphql.graphql(schema, query, variables={'i': object()})

print(result.errors)
```

This gives a TypeError("Object of type 'object' is not JSON serializable") instead of  a GraphQLError("Variable '$i' got invalid value...; Expected type I to be a dict.").

That's why I resorted to repr(). The custom inspect() function will not reveal as much as repr().
