### ISSUE TITLE
Does 'to_dict' will be implemented in graphql-core-next?

### ISSUE THREAD

**Issue by yanghg-basefx** [graphql-python/graphql-core-next#17]
I raise an issue before [Out of memory when wrong use graphql with dataloader](https://github.com/graphql-python/graphql-core/issues/219), but now I find this repo and `to_dict` is not exist in `ExecutionResult`. Does it will be implemented? If not, please close that issue, and I will remove it in my project.

But GraphQL-Server is [using this function](https://github.com/graphql-python/graphql-server-core/blob/master/graphql_server/__init__.py#L154), please note.

Thanks so much!

**Comment by Cito** [comment]
This just returns a dictionary with error and data as keys (instead of the named tuple), and it formats the errors. I don't find this really useful, and it does two things at once which has always a certain smell.

I'd like to get input from @syrusakbary - can this be changed in GraphQL-Server to make it compatible? Or should I really add this to graphql-core-next?

**Comment by Cito** [comment]
There will be a new version of GraphQL-server-core based on GraphQL-core-next (https://github.com/graphql-python/graphql-server-core/issues/20), which will probably not need this, or maybe we will add it then if necessary/reasonable.
