### ISSUE TITLE
Exceptions in subscribe() are not handled by executor

### ISSUE THREAD

**Issue by rafalp** [graphql-python/graphql-core-next#30]
Hello!

When testing the subscriptions we've noticed that exceptions raised in `subscribe()` are not handled by the query executor, instead they come back up outside of `graphql`, when we are consuming the results to create an HTTP response, with `Task exception was never retrieved` being logged by Python to console.

Quick fix we did for this was wrapping whole loop in `try/except` and handling those exceptions there, but this has obvious downside of not having `GraphQLError` with path and location.

**Comment by Cito** [comment]
Thanks for reporting. Will look into this when I find some time.

**Comment by rafalp** [comment]
Here is repro: https://github.com/rafalp/graphql-core-next-30

**Comment by Cito** [comment]
Hi @rafalp - finally found some time to look into this. I understand your problem, but as far as I see, this is the expected behavior and in line with the spec.

When you provide a `response` function to produce the [response stream](https://graphql.github.io/graphql-spec/draft/#sec-Response-Stream), then errors are in fact passed to the client (see points 5. and 6.) as part of the `GraphQLResult`. But the `subscribe` function in your example is used for creating the [source stream](https://graphql.github.io/graphql-spec/draft/#sec-Source-Stream). As far as I see, the specs do not say explicitly what should be done with errors in the source stream. But there is nothing about passing them to the response stream.

The reference implementation passes errors in the response stream to the client and errors in the source stream to the server. You can see this is the expected behavior in these tests in GraphQL.js: It [should handle error during execution of source event](https://github.com/graphql/graphql-js/blob/110d0c18324402a80c4d6059552124a01ca08feb/src/subscription/__tests__/subscribe-test.js#L806) but it [should pass through error thrown in source event stream](https://github.com/graphql/graphql-js/blob/110d0c18324402a80c4d6059552124a01ca08feb/src/subscription/__tests__/subscribe-test.js#L883
). Your example corresponds to the second test - that's why the error is passed through to you.

You could argue that the specs should be amended and errors should be handed over to the response stream. But you will need to create a [GraphQL.js issue](https://github.com/graphql/graphql-js/issues) for this. The goal of graphql-core-next is to just replicate the behavior of GraphQL.js.
