### ISSUE TITLE
Get schema data for query fields?

### ISSUE THREAD

**Issue by astronouth7303** [graphql-python/graphql-core-next#52]
Is there a standard way to get the schema information (type, directives) for a query node/leaf?

Concretely, I'm looking at GitHub's GraphQL, and there's two things I would like to be able to do:

* Handle custom scalars: GitHub defines a handful of custom scalars (a few date/time types, a few URL types, a structured-data blob)
    * Serialization: Look at the types in the query variables, traverse, find serializers for the scalars, apply to data
    * Deserialization: Look at types in the query body, traverse, find deserializers for the scalars, apply to data
* Directives: Github defines an `@preview()` with data that needs to be conveyed in the HTTP headers. I would like to be able to examine a query, get the directives, and pull out the appropriate information

I think the thing I would like is a utility to walk a query (field-by-field) and get the type information for that field.

**Comment by Cito** [comment]
You can run the query you get with `utilities.get_introspection_query` against GitHub's schema. You can then run `utilities_build_client_schema` on the introspection result to replicate that schema. You can use a visitor to walk through your query, and check the types against the schema. The `validation.rules` give some examples how to write such visitors. But it's a bit difficult and unfortunately I don't have enough time to help you more.

I suggest that you raise such questions as graphql/graphql-js issue, or on StackOverflow with graphql-js tag, or on the GraphQL slack, there you will find more people to give competent answers. Since graphql-core is a 1:1 port, it is easy to transfer the solution from JavaScript to Python (or you can also ask here for Porting problems if needed). Also, if it turns out that functionality should be added to the library, this should happen on the GraphQL.js side from where it will be ported here.
