### ISSUE TITLE
Custom scalars using numpy arrays fail is_nullish() test

### ISSUE THREAD

**Issue by thomascobb** [graphql-python/graphql-core-next#59]
I have a custom scalar type for a numpy array:
```python
def serialize_ndarray(value):
    return dict(
        numberType=value.dtype.name.upper(),
        base64=base64.b64encode(value).decode()
    )

ndarray_type = GraphQLScalarType("NDArray", serialize=serialize_ndarray)
```
`is_nullish()` does an inequality test on values to work out if they are NaN:
```python
def is_nullish(value: Any) -> bool:
    """Return true if a value is null, undefined, or NaN."""
    return value is None or value is INVALID or value != value
```
Unfortunately, numpy arrays break this because they override `__eq__` to return a pointwise equality array rather than a boolean.

The comment for `is_nullish()` suggests that `value != value` is checking for NaN. If this is the case we could replace it with:
```python
def is_nan(value):
    """Return true if a value is NaN"""
    try:
        return math.isnan(value)
    except TypeError:
        return False

def is_nullish(value: Any) -> bool:
    """Return true if a value is null, undefined, or NaN."""
    return value is None or value is INVALID or is_nan(value)
```
Would this be acceptable? I can provide a PR if it is.

**Comment by Cito** [comment]
Right, this `value != value` is a bit obscure - it has been taken over 1:1 from JavaScript. Not sure why they test it that way, probably because `isNaN()` was only added to the language in ES 6.

I'm not against changing this and using `math.isnan` instead. However, I'd rather avoid creating an exception and do something like `... or (isinstance(value, float) and isnan(value))` instead.

We should also add a test that `is_nullish(value) is False` for some custom object with value != value , that would simulate the numpy array. Feel free to send a PR, otherwise I'll care about this.

**Comment by Cito** [comment]
Nice, thank you! 👍
